version: '3.8'

services:
  # Nginx 反向代理服务
  nginx:
    image: registry.cn-chengdu.aliyuncs.com/pzl_devops/nginx:alpine
    container_name: zabbixwatch-nginx
    ports:
      - "8088:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - zabbixwatch-web
      - zabbixwatch-api
    restart: unless-stopped
    networks:
      - zabbix-network

  # 前端Web服务 - 使用预构建镜像
  zabbixwatch-web:
    image: registry.cn-chengdu.aliyuncs.com/pzl_devops/zabbix-watch-web:latest
    container_name: zabbixwatch-web
    expose:
      - "80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    networks:
      - zabbix-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # 后端API服务 - 使用预构建镜像
  zabbixwatch-api:
    image: registry.cn-chengdu.aliyuncs.com/pzl_devops/zabbix-watch-api-en:latest
    container_name: zabbixwatch-api
    expose:
      - "5000"
    environment:
      # 时区配置
      - TZ=Asia/Shanghai
      
      # Flask配置
      - FLASK_DEBUG=false
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-your-secret-key-change-in-production}
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      
      # JWT配置
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-very-secret-jwt-key-change-in-production}
      - JWT_EXPIRATION_HOURS=24
      
      # Zabbix配置
      - ZABBIX_URL=${ZABBIX_URL:-http://your-zabbix-server/zabbix}
      - ZABBIX_USERNAME=${ZABBIX_USERNAME:-Admin}
      - ZABBIX_PASSWORD=${ZABBIX_PASSWORD:-your-zabbix-password}
      
      # 数据库配置
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER:-zabbixface}
      - DB_PASSWORD=${DB_PASSWORD:-zabbixface}
      - DB_NAME=${DB_NAME:-zabbixwatch}
      
      # 数据收集配置
      - COLLECTION_INTERVAL=${COLLECTION_INTERVAL:-300}
      - MAX_RETRIES=3
      - RETRY_DELAY=5
      
      # 会话配置
      - SESSION_TIMEOUT=3600
      
      # 日志配置
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/zabbixwatch.log
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zabbix-network

  # MySQL 数据库服务
  mysql:
    image: registry.cn-chengdu.aliyuncs.com/pzl_devops/mysql:8.0
    container_name: zabbixwatch-db
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-zabbixface}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbixwatch}
      - MYSQL_USER=${MYSQL_USER:-zabbixface}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbixface}
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      - ./mysql/conf.d:/etc/mysql/conf.d:ro
      - ./logs/mysql:/var/log/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "3366:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max-connections=200
      --slow-query-log=1
      --slow-query-log-file=/var/log/mysql/slow.log
      --long-query-time=2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-zabbixface}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  mysql_data:
    driver: local